(package "sideline-racket"
         "0.1.0"
         "Show racket result with sideline")

(website-url "https://github.com/emacs-sideline/sideline-racket")
(keywords "convenience")

(package-file "sideline-racket.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "28.1")
(depends-on "sideline")
(depends-on "racket-mode")
